config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  resources :games, except: [:delete]
  resources :react_games, except: [:delete]
  resources :check_cells, only: :create

end

app/models/cell.rb
class Cell < ActiveRecord::Base
  belongs_to :game

  validates :x, presence: true
  validates :y, presence: true
  validates :value, numericality: { greater_than_or_equal_to: -1, less_than_or_equal_to: 8 }
end

app/models/game.rb
class Game < ActiveRecord::Base
  MAXIMUM_SIZE = 20
  MAXIMUM_BOMBS_COUNT = 90

  has_many :cells

  validates :username, presence: true
  validates :bombs_count, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: MAXIMUM_BOMBS_COUNT }
  validates :fields_height, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: MAXIMUM_SIZE }
  validates :fields_width, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: MAXIMUM_SIZE }

  self.per_page = 10

  def safety_cells_count
    Rails.cache.fetch(self) do
      (fields_height * fields_width) - bombs_count
    end
  end

  def finished?
    cells.where(open: true).count == safety_cells_count
  end

  def win
    update(lost: false)
    cells.update_all(open: true)
  end

  def loose
    update(lost: true)
    cells.update_all(open: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/check_cells_controller.rb
class CheckCellsController < ApplicationController
  before_action :initialize_cell, :initialize_checker

  def create
    @attemption_checker.perform
    respond_to do |format|
      format.json { render json: { cells: @cell.game.decorate.cells_data } }
    end
  end

  def edit
  end

  private

  def initialize_cell
    @cell = Cell.find_by(id: params[:id])
  end

  def initialize_checker
    @attemption_checker = AttemptionChecker.new(cell: @cell)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :initialize_game, only: :edit

  def create
    @new_game = Game.new(game_attributes)
    if @new_game.save!
      redirect_to edit_game_path(@new_game)
    else
      redirect_to '/'
    end
  end

  def edit
    respond_to do |format|
      format.text { render text: @game.decorate.make_grid }
      format.html
    end
  end

  private

  def game_attributes
    params.require(:new_game).permit(:username, :bombs_count, :fields_height, :fields_width)
  end

  def set_game
    @game = Game.includes(:cells).find(params[:id])
  end

  def initialize_game
    set_game
    GameInitializer.new(game: @game).perform
    @game.reload
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @games = Game.paginate(:page => params[:page])
  end
end

app/controllers/react_games_controller.rb
class ReactGamesController < GamesController
  def edit
    respond_to do |format|
      format.text { render text: @game.decorate.make_grid }
      format.html
    end
  end

  def initialize_game
    set_game
    GameInitializer.new(game: @game).perform
    @game.reload
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def run_on_near_cells(&block)
    [-1, 0, 1].each do |x|
      [-1, 0, 1].each do |y|
        next if x == 0 && y == 0
          yield(x, y)
      end
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/games/edit.html.slim
table.status
  tr
    td = "#{@game.username}"
    td class="game_status #{@game.decorate.status_class}" = "#{@game.decorate.status_message}"
    td = link_to 'На главную', root_path
hr
#field game-id=params[:id]
  = @game.decorate.make_grid

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SapperRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="react.js"></script>
  <script src="react-dom.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.24/browser.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/_game.html.slim
tr
  td = game.username
  td class="game_status #{game.decorate.status_class}" = "#{game.decorate.status_message}"
  td = game.decorate.opened_cells
  td
    = link_to 'Simple', edit_game_path(game)
    | /
    = link_to 'React', edit_react_game_path(game)

app/views/main/index.html.slim
h1 Сапер
= simple_form_for :new_game, url: games_path, method: :post do |f|
  = f.input :username
  = f.input :bombs_count
  = f.input :fields_height
  = f.input :fields_width
  = f.submit 'Сохранить'
hr
- if @games.any?
  h2 История Игр.
  table.games
    tr
      th Пользователь
      th Статус
      th Полей открыто
      th Ссылки на игру.
    = render partial: 'main/game', collection: @games

  = will_paginate @games

app/views/react_games/edit.html.erb
<h2>Реакт велик </h2>
<div id="sapper"></div>
<script type="text/babel">
  ReactDOM.render(<GameField cells={ <%= @game.decorate.cells_data %> } fields_height={ <%= @game.fields_height %> } fields_width={ <%= @game.fields_width %> }/>, document.getElementById('sapper'));
</script>